#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets start_IBUF]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[5]}]
# set_property PACKAGE_PIN G12 [get_ports {data_dig[0]}]
# set_property PACKAGE_PIN H13 [get_ports {data_dig[1]}]
# set_property PACKAGE_PIN M12 [get_ports {data_dig[2]}]
# set_property PACKAGE_PIN N13 [get_ports {data_dig[3]}]
# set_property PACKAGE_PIN N14 [get_ports {data_dig[4]}]
# set_property PACKAGE_PIN N11 [get_ports {data_dig[5]}]

set_property PACKAGE_PIN T10 [get_ports {key[3]}]
set_property PACKAGE_PIN R11 [get_ports {key[2]}]
set_property PACKAGE_PIN T12 [get_ports {key[1]}]
set_property PACKAGE_PIN R12 [get_ports {key[0]}]
set_property PACKAGE_PIN T5 [get_ports {state_led[3]}]
set_property PACKAGE_PIN R7 [get_ports {state_led[2]}]
set_property PACKAGE_PIN R8 [get_ports {state_led[1]}]
set_property PACKAGE_PIN P9 [get_ports {state_led[0]}]
set_property PACKAGE_PIN R10 [get_ports {row[3]}]
set_property PACKAGE_PIN P10 [get_ports {row[2]}]
set_property PACKAGE_PIN M6 [get_ports {row[1]}]
set_property PACKAGE_PIN K3 [get_ports {row[0]}]
set_property PACKAGE_PIN D4 [get_ports clk]
set_property PACKAGE_PIN F3 [get_ports rstv]
set_property PACKAGE_PIN T9 [get_ports env]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstv]
set_property IOSTANDARD LVCMOS33 [get_ports env]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
# set_property PACKAGE_PIN L13 [get_ports {data_seg[7]}]
# set_property PACKAGE_PIN M14 [get_ports {data_seg[6]}]
# set_property PACKAGE_PIN P13 [get_ports {data_seg[5]}]
# set_property PACKAGE_PIN K12 [get_ports {data_seg[4]}]
# set_property PACKAGE_PIN K13 [get_ports {data_seg[3]}]
# set_property PACKAGE_PIN L14 [get_ports {data_seg[2]}]
# set_property PACKAGE_PIN N12 [get_ports {data_seg[1]}]
# set_property PACKAGE_PIN P11 [get_ports {data_seg[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[0]}]

set_property PACKAGE_PIN L2 [get_ports buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]

set_property IOSTANDARD LVCMOS33 [get_ports {liushui_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {liushui_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {liushui_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {liushui_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {liushui_led[4]}]
set_property PACKAGE_PIN T2 [get_ports {liushui_led[0]}]
set_property PACKAGE_PIN R1 [get_ports {liushui_led[1]}]
set_property PACKAGE_PIN G5 [get_ports {liushui_led[2]}]
set_property PACKAGE_PIN H3 [get_ports {liushui_led[3]}]
set_property PACKAGE_PIN E3 [get_ports {liushui_led[4]}]



set_property PACKAGE_PIN N11 [get_ports {data_dig[5]}]
set_property PACKAGE_PIN N14 [get_ports {data_dig[4]}]
set_property PACKAGE_PIN N13 [get_ports {data_dig[3]}]
set_property PACKAGE_PIN M12 [get_ports {data_dig[2]}]
set_property PACKAGE_PIN H13 [get_ports {data_dig[1]}]
set_property PACKAGE_PIN G12 [get_ports {data_dig[0]}]

set_property PACKAGE_PIN P11 [get_ports {data_seg[7]}]
set_property PACKAGE_PIN N12 [get_ports {data_seg[6]}]
set_property PACKAGE_PIN L14 [get_ports {data_seg[5]}]
set_property PACKAGE_PIN K13 [get_ports {data_seg[4]}]
set_property PACKAGE_PIN K12 [get_ports {data_seg[3]}]
set_property PACKAGE_PIN P13 [get_ports {data_seg[2]}]
set_property PACKAGE_PIN M14 [get_ports {data_seg[1]}]
set_property PACKAGE_PIN L13 [get_ports {data_seg[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_dig[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_seg[0]}]

# create_debug_core u_ila_0 ila
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
# set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
# set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
# set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
# set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
# set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
# set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
# set_property port_width 1 [get_debug_ports u_ila_0/clk]
# connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
# set_property port_width 32 [get_debug_ports u_ila_0/probe0]
# connect_debug_port u_ila_0/probe0 [get_nets [list {u2/cnt[0]} {u2/cnt[1]} {u2/cnt[2]} {u2/cnt[3]} {u2/cnt[4]} {u2/cnt[5]} {u2/cnt[6]} {u2/cnt[7]} {u2/cnt[8]} {u2/cnt[9]} {u2/cnt[10]} {u2/cnt[11]} {u2/cnt[12]} {u2/cnt[13]} {u2/cnt[14]} {u2/cnt[15]} {u2/cnt[16]} {u2/cnt[17]} {u2/cnt[18]} {u2/cnt[19]} {u2/cnt[20]} {u2/cnt[21]} {u2/cnt[22]} {u2/cnt[23]} {u2/cnt[24]} {u2/cnt[25]} {u2/cnt[26]} {u2/cnt[27]} {u2/cnt[28]} {u2/cnt[29]} {u2/cnt[30]} {u2/cnt[31]}]]
# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
# set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
# set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
# connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
